# Generated by Django 3.2.7 on 2021-10-29 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_special',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Special User'),
        ),
    ]
